name: Weekly CI/CD Check

on:
  #schedule:
    #- cron: '0 0 * * 1'  # Every Monday at midnight
  workflow_dispatch:

jobs:
  check-and-copy:
    runs-on: ubuntu-latest

    steps:
      - name: Copy Repository to CustomKlipy
        run: git clone https://github.com/Oleksandr-science/test1.git
      - name: Copy Repository to CustomKlipy
        run: git clone https://github.com/Klipper3d/klipper.git
      - name: Copy Repository to CustomKlipy
        run: |
          mkdir -p test1/rev-$(date +%Y%m%d)
          mv klipper test1/rev-$(date +%Y%m%d)
          cd test1
          git config --global user.email "3darduin@gmail.com"
          git config --global user.name "Oleksandr-science"
          git add .
          git commit -m "Weekly update from Klipper repository"
          git push
         
          
