name: Push Changes to GitHub

on: 
  push:
    branches: [ main ]  # Trigger the workflow when changes are pushed to the main branch

jobs:
  # open-issue:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     issues: write
  #   steps:
  #     - run: |
  #         gh issue --repo ${{ github.repository }} \
  #           create --title "Issue title" --body "Issue body"
  #       env:
  #         GH_TOKEN: ${{ secrets.TOKEN }}
          
  build:  # Name of the job
    runs-on: ubuntu-latest

    steps:  
      - uses: actions/checkout@v4  # Check out your repository code

      - name: temp file
        run: |
          ls -lah
          touch /home/runner/test1.txt
          pwd > /home/runner/test1.txt
          cat /home/runner/test1.txt

      - name: Commit and Push Changes
        run: |
          echo $GH_TOKEN > /home/runner/.ssh/clone
          chmod 400 /home/runner/.ssh/clone
          git config --global user.email "3darduin@gmail.com"
          git config --global user.name "Oleksandr-science"
          git add .  # Add all modified files
          git commit -m "Automatic update from GitHub Actions"
          eval `ssh-agent -s`
          ssh-add /home/runner/.ssh/clone
          git push git@github.com:Oleksandr-science/test1.git
        env:
          GH_TOKEN: ${{ secrets.CLONE }}
