name: Push Changes to GitHub

on: 
  push:
    branches: [ main ]  # Trigger the workflow when changes are pushed to the main branch

jobs:
  build:  # Name of the job
    runs-on: ubuntu-latest

    steps:  
      - uses: actions/checkout@v4  # Check out your repository code

      - name: Install dependencies
        run: ls -la

  
