name: Push Changes to GitHub

on: 
  push:
    branches: [ main ]  # Trigger the workflow when changes are pushed to the main branch

jobs:
  open-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - run: |
          gh issue --repo ${{ github.repository }} \
            create --title "Issue title" --body "Issue body"
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
          
  build:  # Name of the job
    runs-on: ubuntu-latest

    steps:  
      - uses: actions/checkout@v4  # Check out your repository code

      - name: Install dependencies
        run: pwd > test1.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "Oleksandr-science"
          git config --global user.email "3darduin@gmail.com"
          git add .  # Add all modified files
          git commit -m "Automatic update from GitHub Actions"
          git push origin main

  
